MTDSIM-44
cits3200-team37/mtd pull request #50
Opened 2023-09-21 07:29 UTC by Vobrymn

Update to /simulate endpoint doc to reflect the new return object and its details

2023-10-02 13:12 UTC, benvarian commented
is this ready to be looked at again

2023-10-07 16:20 UTC, nicodeas requested changes

2023-10-07 16:20 UTC, nicodeas commented on server/Documentation/docs/backend/endpoints.md
> -  }
My stuff is still deleted.

2023-10-07 16:20 UTC, nicodeas commented on server/Documentation/docs/backend/endpoints.md
> +'name': {0: 'CompleteTopologyShuffle', 1: 'OSDiversity', 2: 'OSDiversity'},
heres a field called name?

2023-10-07 16:20 UTC, nicodeas commented on server/Documentation/docs/backend/endpoints.md
> +'name': {0: 'CompleteTopologyShuffle', 1: 'OSDiversity', 2: 'OSDiversity'},
could you leave it in the format that it was left before? i think this is complicated

2023-10-07 16:20 UTC, nicodeas commented on server/Documentation/docs/backend/endpoints.md
> +'executed_at': {0: 'network', 1: 'application', 2: 'application'}
is there a field for this?

2023-10-07 16:20 UTC, nicodeas commented on server/api/app.py
👍🏻

2023-10-12 03:11 UTC, benvarian commented
is this issue ready to be reviewed again, if so please close all of nicks requirements and itll be looked at soon

2023-10-12 14:20 UTC, Vobrymn commented on server/Documentation/docs/backend/endpoints.md
> +'name': {0: 'CompleteTopologyShuffle', 1: 'OSDiversity', 2: 'OSDiversity'},
This is the simplest i can make it if you want a complete sample response for each of the things we are sending to the front end. before you only had it for the network graph.

2023-10-12 14:21 UTC, Vobrymn commented on server/Documentation/docs/backend/endpoints.md
> +'executed_at': {0: 'network', 1: 'application', 2: 'application'}
a field?

2023-10-12 14:27 UTC, Vobrymn commented on server/Documentation/docs/backend/endpoints.md
> -  }
everything in main is here, not sure whay im missing

2023-10-16 01:34 UTC, merged