Mtdsim 93 Refactor front end code urls
cits3200-team37/mtd pull request #66
Opened 2023-09-27 05:33 UTC by FearMyCode

2023-09-29 15:42 UTC, nicodeas commented
can you please create a `.env.example` file with default values ie what they are now

2023-09-29 15:42 UTC, nicodeas commented
then people can just copy that into a .env file for local development

2023-09-29 15:43 UTC, nicodeas commented
then you can update setup information / steps with your new steps. 😄

2023-09-30 13:15 UTC, Vobrymn approved these changes

2023-09-30 15:20 UTC, Vobrymn requested changes

2023-09-30 15:20 UTC, Vobrymn commented on client/src/stores/simulation.js
> -      }
these params seem to have been accidentally deleted

2023-09-30 15:22 UTC, Vobrymn commented on client/src/stores/simulation.js
> -      }
probably by me whoops

2023-10-01 08:44 UTC, Vobrymn approved these changes

2023-10-01 08:44 UTC, merged