modified simulation.js for additional parameters
cits3200-team37/mtd pull request #81
Opened 2023-09-30 08:40 UTC by crystalycteh

2023-09-30 14:30 UTC, FearMyCode requested changes
You might also consider looping through the parameters property. It can enhance readability and scalability.

2023-09-30 14:30 UTC, FearMyCode commented on client/src/stores/simulation.js
> +      }
Change this back to this.parameters.scheme.toLowerCase(). Scheme is not a number

2023-10-01 03:40 UTC, crystalycteh commented on client/src/stores/simulation.js
> +      }
ok

2023-10-02 13:12 UTC, benvarian commented
if this is ready to be looked at again, fix merge conflicts and let someone know

2023-10-03 04:16 UTC, closed without merging