Proto sim explainer, fixed some bounding issues
cits3200-team37/mtd pull request #83
Opened 2023-09-30 09:48 UTC by Vobrymn

Prototype explanation on the simulation page. Needs fine tuning. Some fixes with the border expanding and making the screen scrollable into space off screen (i.e white-space)

2023-09-30 09:54 UTC, Vobrymn reviewed
also made param bar scrollbar hidden, changeable in style.css

2023-09-30 14:43 UTC, benvarian commented on client/index.html
> +    <div id="app" class="overflow-hidden"></div>
what does overflow-hidden change

2023-09-30 15:01 UTC, benvarian commented on client/src/style.css
> +  .hide-scrollbar {
can we not get rid off the scrollbar, its an important ui feature for a reason

2023-09-30 15:03 UTC, benvarian commented on client/src/views/SimulationView.vue
> +        WIP: fix after param finalisation. <br>
- i would say the param bar is finalised so do the rest now and cleanup the todo + wip comments
- would also merge main in as michael added something to this page and wanna make sure that it blends together well

2023-10-02 13:00 UTC, benvarian commented on client/src/style.css
> +    --complementary-color: 183 230 240;
please merge main in and use michaels scrollbar, this color combo is terrible

2023-10-02 13:02 UTC, benvarian commented on client/src/views/SimulationView.vue
> +                network<br /><span class="text-xs">Default: </span>
no default supplied

2023-10-02 13:02 UTC, benvarian commented on client/src/views/SimulationView.vue
> +                network<br /><span class="text-xs">Default: </span>
seed also isnt provided in this lil thing

2023-10-02 13:03 UTC, benvarian commented on client/src/views/SimulationView.vue
> +                Target Layer: the layer where the target host will be located<br /><span
have a default answer for this pls like the other ones

2023-10-02 13:04 UTC, benvarian commented on client/src/views/SimulationView.vue
> +                Total Subnets: the number of sub-networks in the simulated
if i am to use the default examples for my values mainly total nodes=50, endpoints=45, the sim wont run cause subnets needs to be over 4 and cant be 5

2023-10-02 13:05 UTC, benvarian commented on client/src/views/SimulationView.vue
> +                Total Subnets: the number of sub-networks in the simulated
once these are done ill look again

2023-10-02 13:09 UTC, benvarian commented on client/src/stores/simulation.js
> +const BACKEND_URL = "http://localhost:8001";
please remove this stuff as michael still hasnt supplied his env file after a day so we have to assume he aint got one , so just hardcode it for now like it was before and we can get someone to deal with the rest later

2023-10-02 14:10 UTC, Vobrymn commented on client/src/views/SimulationView.vue
> +                network<br /><span class="text-xs">Default: </span>
For Scheme? there is no default, it is required

2023-10-02 14:18 UTC, Vobrymn commented on client/src/stores/simulation.js
> +const BACKEND_URL = "http://localhost:8001";
this is already hard coded, ill just remove the comment

2023-10-04 01:52 UTC, nicodeas requested changes

2023-10-04 01:52 UTC, nicodeas commented on server/api/app.py
please dont remove my error handling

2023-10-04 01:52 UTC, nicodeas commented on server/experiments/run.py
> +        total_nodes = 50
remove. Not everthing should be default

2023-10-04 09:47 UTC, benvarian commented on client/src/components/DropDown.vue
> -    default: () => ["Random", "Simultaneous", "Alternative", "Single", "None"],
add the defaults back in, this component is legit only gonna get used here so theres no point is specifying params in parent

2023-10-04 09:47 UTC, benvarian commented on client/src/components/DropDown.vue
> -    default: () => ["Random", "Simultaneous", "Alternative", "Single", "None"],
same with the other defaults, no need to pass from parent if theres only one use case for the component

2023-10-04 09:48 UTC, benvarian commented on client/src/stores/simulation.js
> +      console.log(reqBody);
remove console.log

2023-10-04 09:49 UTC, benvarian commented on client/src/stores/simulation.js
> +      if (this.parameters.totalNodes) {
whats the purpose for all these if statements, all the data should be validated before coming into the store

2023-10-04 09:55 UTC, benvarian commented on client/src/style.css
> +    --complementary-color: 0 204 153;
change the name of complementary to something more descriptive as its very open ended as to what it actually does

2023-10-04 11:14 UTC, Vobrymn commented on client/src/stores/simulation.js
> +      if (this.parameters.totalNodes) {
its not validation, its just checking if they specified a value or not, if not, dont even bother sending a rq value, use backend default

2023-10-04 11:17 UTC, Vobrymn commented on client/src/style.css
> +    --complementary-color: 0 204 153;
button-color

2023-10-04 11:23 UTC, Vobrymn commented on client/src/components/DropDown.vue
> -    default: () => ["Random", "Simultaneous", "Alternative", "Single", "None"],
ok

2023-10-04 11:28 UTC, Vobrymn commented on client/src/stores/simulation.js
> +      if (this.parameters.totalNodes) {
Number(null) or Number(str) results in 0 or NaN, not None

2023-10-04 11:28 UTC, Vobrymn commented on client/src/stores/simulation.js
> +      console.log(reqBody);
done

2023-10-04 11:35 UTC, Vobrymn commented on client/src/views/SimulationView.vue
> +          class="flex-2 m-10 border rounded p-4 h-[calc(50vh)] overflow-y-auto bg-navbar-primary scrollbar"
done

2023-10-04 11:48 UTC, benvarian commented on client/src/style.css
> +    --button-color: 0 174 153;
Can we not use button either, it implies it’s the color for every button, use something like sub color or something along those lines

2023-10-05 08:17 UTC, nicodeas approved these changes

2023-10-05 08:17 UTC, merged